### ISSUE TITLE
ImportError: No module named 'dataLoader'

### ISSUE THREAD

**Issue by fayazdharejo** [PrathamSoni/CASRCNN#1]
ImportError: No module named 'dataLoader'  . i am facing this issue. can you pleaase help me out

**Comment by PrathamSoni** [comment]
Sorry about that. I have added it now!

**Comment by fayazdharejo** [comment]
> 
> 
> Sorry about that. I have added it now!

reduce() of empty sequence with no initial value

**Comment by PrathamSoni** [comment]
Can you please open another issue stating where this error occurrs? It will help me better implement changes as necessary.
